import type {Day1Config} from './day01';

export const DAY3_EN: Day1Config = {
  id: 'Day3EN',
  flag: 'us',
  voFile: 'd3-vo-en.mp3',
  cues: [
    {from: 0.05, to: 2.32, lines: ['YOU JUST ADDED', 'MORE WATER.']},
    {from: 2.32, to: 4.48, lines: ['DID YOU GET', 'MORE PEPTIDE? NO.'], teal: 1},
    {from: 4.48, to: 9.05, lines: ['5 MG + 2 ML', '= 2.5 MG/ML'], teal: 1},
    {from: 9.05, to: 13.54, lines: ['SAME 5 MG + 5 ML', '= 1 MG/ML'], teal: 1},
    {from: 13.54, to: 15.26, lines: ['MORE WATER', 'ADDED NOTHING.']},
    {from: 15.26, to: 17.92, lines: ['IT ONLY SPREAD THE', 'SAME PEPTIDE THINNER.']},
    {from: 17.92, to: 20.3, lines: ['THE AMOUNT', 'STAYS 5 MG.'], teal: 1},
    {from: 20.3, to: 22.37, lines: ['ONLY THE', 'CONCENTRATION CHANGED.']},
    {from: 22.37, to: 24.31, lines: ['BUDDYPEPT', 'TRACKS BOTH.'], teal: 1},
  ],
  cards: {
    from: 4.48,
    to: 13.54,
    a: {title: '5 mg', sub: '+ 2 mL', value: '2.5 mg/mL'},
    b: {title: '5 mg', sub: '+ 5 mL', value: '1 mg/mL'},
    bFrom: 9.05,
  },
  info: {
    from: 13.54,
    to: 24.31,
    top: 'More water added nothing',
    mid: 'STILL 5 MG',
    bottom: 'Only the concentration changed',
  },
  buddy: {from: 2.32, to: 24.31},
  endFrom: 24.31,
  dayChip: {from: 26.56, label: 'DAY 3 OF 10'},
  disclaimer: 'Educational tool. Not medical advice. For research purposes only.',
  durationSec: 43,
};

export const DAY3_PT: Day1Config = {
  id: 'Day3PT',
  flag: 'br',
  voFile: 'd3-vo-pt.mp3',
  cues: [
    {from: 0.1, to: 2.84, lines: ['VOCÊ ACABOU DE', 'COLOCAR MAIS ÁGUA.']},
    {from: 2.84, to: 5.03, lines: ['GANHOU MAIS', 'PEPTÍDEO? NÃO.'], teal: 1},
    {from: 5.03, to: 9.47, lines: ['5 MG + 2 ML', '= 2.5 MG/ML'], teal: 1},
    {from: 9.47, to: 13.59, lines: ['MESMOS 5 MG + 5 ML', '= 1 MG/ML'], teal: 1},
    {from: 13.59, to: 15.66, lines: ['MAIS ÁGUA NÃO', 'ACRESCENTOU NADA.']},
    {from: 15.66, to: 17.75, lines: ['SÓ ESPALHOU O', 'MESMO PEPTÍDEO.']},
    {from: 17.75, to: 20.41, lines: ['A QUANTIDADE', 'CONTINUA 5 MG.'], teal: 1},
    {from: 20.41, to: 22.24, lines: ['SÓ A CONCENTRAÇÃO', 'MUDOU.']},
    {from: 22.24, to: 24.88, lines: ['O BUDDYPEPT', 'ACOMPANHA OS DOIS.'], teal: 1},
  ],
  cards: {
    from: 5.03,
    to: 13.59,
    a: {title: '5 mg', sub: '+ 2 mL', value: '2.5 mg/mL'},
    b: {title: '5 mg', sub: '+ 5 mL', value: '1 mg/mL'},
    bFrom: 9.47,
  },
  info: {
    from: 13.59,
    to: 24.88,
    top: 'Mais água não acrescentou nada',
    mid: 'AINDA 5 MG',
    bottom: 'Só a concentração mudou',
  },
  buddy: {from: 2.84, to: 24.88},
  endFrom: 24.88,
  dayChip: {from: 27.25, label: 'DIA 3 DE 10'},
  disclaimer: 'Ferramenta educacional. Não é orientação médica. Somente para fins de pesquisa.',
  durationSec: 45,
};

export const DAY3_ES: Day1Config = {
  id: 'Day3ES',
  flag: 'mx',
  voFile: 'd3-vo-es.mp3',
  cues: [
    {from: 0.1, to: 3.1, lines: ['ACABAS DE AGREGAR', 'MÁS AGUA.']},
    {from: 3.1, to: 6.77, lines: ['¿OBTUVISTE MÁS', 'PÉPTIDO? NO.'], teal: 1},
    {from: 6.77, to: 12.06, lines: ['5 MG + 2 ML', '= 2.5 MG/ML'], teal: 1},
    {from: 12.06, to: 17.17, lines: ['MISMOS 5 MG + 5 ML', '= 1 MG/ML'], teal: 1},
    {from: 17.17, to: 19.66, lines: ['MÁS AGUA NO', 'AGREGÓ NADA.']},
    {from: 19.66, to: 22.51, lines: ['SOLO REPARTIÓ EL', 'MISMO PÉPTIDO.']},
    {from: 22.51, to: 26.07, lines: ['LA CANTIDAD SIGUE', 'SIENDO 5 MG.'], teal: 1},
    {from: 26.07, to: 28.71, lines: ['SOLO CAMBIÓ LA', 'CONCENTRACIÓN.']},
    {from: 28.71, to: 32.07, lines: ['BUDDYPEPT LLEVA EL', 'CONTROL DE AMBOS.'], teal: 1},
  ],
  cards: {
    from: 6.77,
    to: 17.17,
    a: {title: '5 mg', sub: '+ 2 mL', value: '2.5 mg/mL'},
    b: {title: '5 mg', sub: '+ 5 mL', value: '1 mg/mL'},
    bFrom: 12.06,
  },
  info: {
    from: 17.17,
    to: 32.07,
    top: 'Más agua no agregó nada',
    mid: 'SIGUEN 5 MG',
    bottom: 'Solo cambió la concentración',
  },
  buddy: {from: 3.1, to: 32.07},
  endFrom: 32.07,
  dayChip: {from: 35.17, label: 'DÍA 3 DE 10'},
  disclaimer: 'Herramienta educativa. No es consejo médico. Solo con fines de investigación.',
  durationSec: 58,
};
